# Generated by Django 5.1.5 on 2025-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='keywords',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='guide',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
