# Generated by Django 5.1.5 on 2025-01-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_member_is_active_member_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
