# Generated by Django 5.1.5 on 2025-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='state',
            field=models.CharField(default='XX', max_length=2),
        ),
    ]
