# Generated by Django 5.1.5 on 2025-02-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_settings_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
