# Generated by Django 5.1.5 on 2025-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0003_bonusbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusbet',
            name='bonus_bet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bonusbet',
            name='bonus_odds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bonusbet',
            name='hedge_bet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bonusbet',
            name='hedge_odds',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bonusbet',
            name='profit_index',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bonusbet',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
