# Generated by Django 5.1.5 on 2025-02-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0004_bonusbet_bonus_bet_bonusbet_bonus_odds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusbet',
            name='hedge_index',
            field=models.FloatField(null=True),
        ),
    ]
