# Generated by Django 5.1.5 on 2025-02-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0005_bonusbet_hedge_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('bonus_bet', models.TextField(null=True)),
                ('bonus_odds', models.IntegerField(null=True)),
                ('hedge_bet', models.TextField(null=True)),
                ('hedge_odds', models.IntegerField(null=True)),
                ('profit_index', models.FloatField(null=True)),
            ],
        ),
    ]
