# Generated by Django 5.1.5 on 2025-02-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0006_secondbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbet',
            name='hedge_index',
            field=models.FloatField(null=True),
        ),
    ]
