# Generated by Django 5.1.5 on 2025-03-01 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0007_secondbet_hedge_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
            ],
        ),
    ]
