# Generated by Django 5.1.5 on 2025-03-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0008_bookie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookie',
            new_name='BookMaker',
        ),
    ]
