# Generated by Django 5.1.5 on 2025-03-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0009_rename_bookie_bookmaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusbet',
            name='bonus_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='bonusbet',
            name='hedge_name',
            field=models.TextField(null=True),
        ),
    ]
