# Generated by Django 5.1.5 on 2025-03-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0010_bonusbet_bonus_name_bonusbet_hedge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusbet',
            name='market',
            field=models.TextField(null=True),
        ),
    ]
