# Generated by Django 5.1.5 on 2025-03-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0011_bonusbet_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbet',
            name='market',
            field=models.TextField(null=True),
        ),
    ]
