# Generated by Django 5.1.5 on 2025-03-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0012_secondbet_market'),
    ]

    operations = [
        migrations.AddField(
            model_name='secondbet',
            name='bonus_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondbet',
            name='hedge_name',
            field=models.TextField(null=True),
        ),
    ]
