# Generated by Django 5.1.5 on 2025-03-03 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0013_secondbet_bonus_name_secondbet_hedge_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('timezome', models.CharField(max_length=50)),
            ],
        ),
    ]
