# Generated by Django 5.1.5 on 2025-03-03 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0014_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='timezome',
            new_name='timezone',
        ),
    ]
