# Generated by Django 5.1.5 on 2025-03-03 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0015_rename_timezome_state_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='state_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finder.state'),
        ),
    ]
