# Generated by Django 5.1.5 on 2025-03-03 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0016_settings_state_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='state',
        ),
    ]
