# Generated by Django 5.1.5 on 2025-03-03 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0017_remove_settings_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='state_key',
            new_name='state',
        ),
    ]
