# Generated by Django 5.1.5 on 2025-03-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0018_rename_state_key_settings_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusbet',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='secondbet',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
