# Generated by Django 5.1.5 on 2025-03-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0019_bonusbet_time_secondbet_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonusbet',
            name='time',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='secondbet',
            name='time',
            field=models.TextField(null=True),
        ),
    ]
