# Generated by Django 5.1.5 on 2025-03-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0020_alter_bonusbet_time_alter_secondbet_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusbet',
            name='sport',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='secondbet',
            name='sport',
            field=models.TextField(null=True),
        ),
    ]
