# Generated by Django 5.1.5 on 2025-03-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0021_bonusbet_sport_secondbet_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.TextField()),
                ('description', models.TextField(null=True)),
                ('code', models.CharField(max_length=50, null=True)),
                ('url', models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
