# Generated by Django 5.1.5 on 2025-05-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0022_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='timezone',
        ),
        migrations.AddField(
            model_name='settings',
            name='timezone',
            field=models.CharField(default='Etc/GMT+6', max_length=50),
        ),
    ]
