# Generated by Django 5.1.5 on 2025-05-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0023_remove_state_timezone_settings_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('market', models.TextField(null=True)),
                ('time', models.TextField(null=True)),
                ('sport', models.TextField(null=True)),
                ('bonus_bet', models.TextField(null=True)),
                ('bonus_odds', models.IntegerField(null=True)),
                ('bonus_name', models.TextField(null=True)),
                ('hedge_bet', models.TextField(null=True)),
                ('hedge_odds', models.IntegerField(null=True)),
                ('hedge_name', models.TextField(null=True)),
                ('hedge_index', models.FloatField(null=True)),
                ('profit_index', models.FloatField(null=True)),
            ],
        ),
    ]
