# Generated by Django 5.1.5 on 2025-05-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0024_profitbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='bookmakers',
            field=models.ManyToManyField(to='finder.bookmaker'),
        ),
        migrations.AddField(
            model_name='state',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
