# Generated by Django 5.1.5 on 2025-05-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0025_state_bookmakers_state_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='bookmakers',
        ),
        migrations.AddField(
            model_name='bookmaker',
            name='states',
            field=models.ManyToManyField(to='finder.state'),
        ),
    ]
