# Generated by Django 5.1.5 on 2025-06-19 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0026_remove_state_bookmakers_bookmaker_states'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('market', models.TextField(null=True)),
                ('time', models.TextField(null=True)),
                ('sport', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker', models.CharField(max_length=100, null=True)),
                ('side', models.CharField(max_length=100, null=True)),
                ('odds', models.IntegerField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finder.event')),
            ],
        ),
    ]
